routes/web.php
<?php
//Auth
Route::get('/', [
    'uses' => 'Auth\LoginController@getLogin',
    'as' => 'login.get',
]);

Route::post('login', [
    'uses' => 'Auth\LoginController@postLogin',
    'as' => 'login.post',
]);

Route::get('logout', [
    'uses' => 'Auth\LoginController@getLogout',
    'as' => 'logout',
]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Super Admin']], function () {
    Route::resource('activity', 'ActivityLogController');

    Route::get('collectors', [
        'uses' => 'SuperAdminController@getCollectors',
        'as' => 'get.collectors',
    ]);

    Route::post('collector', [
        'uses' => 'SuperAdminController@postCollector',
        'as' => 'post.collector',
    ]);

    Route::patch('collector/remove', [
        'uses' => 'SuperAdminController@patchCollectorRemove',
        'as' => 'patch.collector.remove',
    ]);
});


Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Accountant|Super Admin|Collector']], function () {

    Route::get('subscriber/billing/fees', [
        'uses' => 'SuperAdminController@getFees',
        'as' => 'billing.fees',
    ]);

});

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Accountant|Super Admin']], function () {

    Route::resource('billing', 'BillingController');

    Route::resource('statement', 'StatementOfAccountController');

    Route::resource('user-subscriber', 'SubscriberController');

    Route::get('/', [
        'uses' => 'SuperAdminController@getDashboard',
        'as' => 'dashboard',
    ]);

    Route::get('inactive/subscribers', [
        'uses' => 'SuperAdminController@getInactiveSubscribers',
        'as' => 'inactive.subscribers',
    ]);

    Route::patch('subscriber/disconnect/', [
        'uses' => 'SuperAdminController@patchDisconnectSubscriber',
        'as' => 'disconnect.subscriber',
    ]);

    Route::patch('inactive/subscriber/reconnect', [
        'uses' => 'SuperAdminController@patchReconnectSubscriber',
        'as' => 'reconnect.subscriber',
    ]);

    Route::post('pay', [
        'uses' => 'SuperAdminController@postPay',
        'as' => 'post.pay',
    ]);

    Route::get('add/subscriber', [
        'uses' => 'SuperAdminController@getAddSubscriber',
        'as' => 'add.subscriber',
    ]);

    Route::post('store/subscriber', [
        'uses' => 'SuperAdminController@getStoreSubscriber',
        'as' => 'store.subscriber',
    ]);

    Route::get('subscriber/billings/{id}', [
        'uses' => 'SuperAdminController@getSubscriberBillings',
        'as' => 'billings.subscriber',
    ]);

    Route::get('subscriber/payments/{id}', [
        'uses' => 'SuperAdminController@getSubscriberPayments',
        'as' => 'payments.subscriber',
    ]);

    Route::get('subscriber/profile/{id}', [
        'uses' => 'SuperAdminController@getSubscriberProfile',
        'as' => 'profile.subscriber',
    ]);

    Route::get('subscriber/statement-of-account/{id}', [
        'uses' => 'SuperAdminController@getSubscriberStatementOfAccount',
        'as' => 'soa.subscriber',
    ]);

    Route::patch('subscriber/profile/patch/name', [
        'uses' => 'SuperAdminController@patchSubscriberName',
        'as' => 'patch.subscriber.name',
    ]);

    Route::patch('subscriber/patch/contact_number', [
        'uses' => 'SuperAdminController@patchSubscriberContactNumber',
        'as' => 'patch.subscriber.contact_number',
    ]);

    Route::patch('subscriber/patch/date_of_installation', [
        'uses' => 'SuperAdminController@patchSubscriberDateOfInstallation',
        'as' => 'patch.subscriber.date_of_installation',
    ]);

    Route::patch('subscriber/patch/rate', [
        'uses' => 'SuperAdminController@patchSubscriberRate',
        'as' => 'patch.subscriber.rate',
    ]);

    Route::patch('subscriber/patch/address', [
        'uses' => 'SuperAdminController@patchSubscriberAddress',
        'as' => 'patch.subscriber.address',
    ]);

    Route::patch('subscriber/patch/picture', [
        'uses' => 'SuperAdminController@patchSubscriberPicture',
        'as' => 'patch.subscriber.picture',
    ]);

    Route::post('subscriber/transfer', [
        'uses' => 'SuperAdminController@postSubscriberTransfer',
        'as' => 'post.transfer',
    ]);

    Route::get('add/old-subscriber', [
        'uses' => 'SuperAdminController@getAddOldSubscriber',
        'as' => 'add.old.subscriber',
    ]);

    Route::post('add/old-subscriber', [
        'uses' => 'SuperAdminController@postAddOldSubscriber',
        'as' => 'post.add.old.subscriber',
    ]);

    Route::patch('subscriber/billing/update', [
        'uses' => 'SuperAdminController@patchSubscriberBilling',
        'as' => 'patch.subscriber.billing',
    ]);

    Route::get('collector/daily/report', [
        'uses' => 'SuperAdminController@getCollectorDailyReport',
        'as' => 'collector.daily',
    ]);

    Route::get('collector/monthly/report', [
        'uses' => 'SuperAdminController@getCollectorMonthlyReport',
        'as' => 'collector.monthly',
    ]);

    Route::get('collector/daily/report-subscriber', [
        'uses' => 'SuperAdminController@getSubscribersReportDaily',
        'as' => 'collector.daily.subscriber',
    ]);

    Route::get('collector/monthly/report-subscriber', [
        'uses' => 'SuperAdminController@getSubscribersReportMonthly',
        'as' => 'collector.monthly.subscriber',
    ]);

    Route::get('collector/daily-all/report-subscriber', [
        'uses' => 'SuperAdminController@getAllSubscribersReportDaily',
        'as' => 'collector.daily-all.subscriber',
    ]);

    Route::post('deposit', [
        'uses' => 'SuperAdminController@postDeposit',
        'as' => 'post.deposit',
    ]);

});

//////////////////////COLLECTOR////////////////////////////////
Route::get('collector-dashboard/subscribers', [
    'uses' => 'CollectorController@getSubscriber',
    'as' => 'collector.subscribers',
    'middleware' => ['role:Collector'],
]);

Route::post('collector-dashboard/pay', [
    'uses' => 'CollectorController@pay',
    'as' => 'collector.pay',
    'middleware' => ['role:Collector'],
]);

Route::get('collector-dashboard/thank-you-page/{id}', [
    'uses' => 'CollectorController@ty',
    'as' => 'collector.ty',
    'middleware' => ['role:Collector'],
]);

Route::get('collector-performance/payments', [
    'uses' => 'CollectorController@performance',
    'as' => 'collector-performance.payments',
    'middleware' => ['role:Collector'],
]);

Route::get('export-subscribers', function () {
    ini_set('memory_limit', '-1');
    try {
        $user = auth()->user();

        $active_subscribers = App\Subscriber::where('status', 'active')
            ->where('collector', $user->name)
            ->get();

        $new = [];

        foreach($active_subscribers as $k => $v) {
                if(number_format($v->billings->sum('balance'),2) == '0.00') {
                    continue;
                }
                $new[$k]['id'] = $v->id;
                $new[$k]['name'] = $v->name.' '.$v->last_name;
                $new[$k]['address'] = $v->address;
                $new[$k]['contact_number'] = $v->contact_number;
                $new[$k]['balance'] = number_format($v->billings->sum('balance'),2);
                // $new[$k]['sort_balance'] = $v->billings->sum('balance');
                $new[$k]['last_payment'] = @$v->payments()->latest()->first()->date_paid;
                $new[$k]['collector'] = @$v->collector;
        }

        // usort($new, function($a, $b) {
        //     return $a['sort_balance'] <=> $b['sort_balance'];
        // });

        $list = collect($new);

        // $list = $xlist->transform(function(array $item) {
        //     return array_except($item, ['sort_balance']);
        // });

        return (new Rap2hpoutre\FastExcel\FastExcel($list))->download('subscribers_collector.xlsx');
    } catch (Exception $e) {
        echo 'Message: ' .$e->getMessage();
    }

})->name('export.subscribers.collector');

/////////////////////////////////////////////////////////////////


Route::get('dashboard/reports', [
    'uses' => 'SuperAdminController@getReports',
    'as' => 'get.reports',
    'middleware' => ['role:Super Admin'],
]);

Route::get('custom-data-input', [
    'uses' => 'CustomDataInputController@getCustomDataInput',
    'as' => 'get.custom',
    'middleware' => ['role:Accountant'],
]);

Route::post('custom-data-input', [
    'uses' => 'CustomDataInputController@postCustomDataInput',
    'as' => 'post.custom',
    'middleware' => ['role:Accountant'],
]);

Route::get('export-user', function () {
    ini_set('memory_limit', '-1');
    return (new Rap2hpoutre\FastExcel\FastExcel(App\Subscriber::where('status', 'Active')->select(['name', 'last_name', 'specific_address', 'address'])->get()))->download('XXX.xlsx');
});

Route::get('export-billing', function () {
    ini_set('memory_limit', '-1');
    try {
        $active_subscribers = App\Subscriber::where('status', 'active')->get();

        $new = [];

        foreach($active_subscribers as $k => $v) {
                if(number_format($v->billings->sum('balance'),2) == '0.00') {
                    continue;
                }
                $new[$k]['id'] = $v->id;
                $new[$k]['name'] = $v->name.' '.$v->last_name;
                $new[$k]['address'] = $v->address;
                $new[$k]['contact_number'] = $v->contact_number;
                $new[$k]['balance'] = number_format($v->billings->sum('balance'),2);
                $new[$k]['sort'] = $v->billings->sum('balance');
        }

        usort($new, function($a, $b) {
            return $a['sort'] <=> $b['sort'];
        });

        $list = collect($new);

        return (new Rap2hpoutre\FastExcel\FastExcel($list))->download('balance.xlsx');
    } catch (Exception $e) {
        echo 'Message: ' .$e->getMessage();
    }

})->name('export.billing');


Route::get('export-fee', function () {
    ini_set('memory_limit', '-1');
    try {

resources/views/admin/add_old_subscriber.blade.php
@extends('layouts.main')
@section('title', '| Add old subscriber')
@section('content')
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="form-top">
      <div class="form-top-left">
        <h3>Add Old Subscriber (Inactive/Disconnected Subscriber)</h3>
        <p>Fill in the form below:</p>
      </div>
      <div class="form-top-right">
        <i class="fa fa-pencil"></i>
      </div>
    </div> {{-- form-top --}}
    <div class="form-bottom">
      <form role="form" action="{{ route('post.add.old.subscriber') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="status" value="Inactive">
        <input type="hidden" name="billing_status" value="Pending">
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="name" value="{{ old('name') }}" placeholder="First Name..">
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="last_name" value="{{ old('last_name') }}" placeholder="Last Name..">
        </div>
        <div class="form-group">
          <textarea required class="bci-custom-input form-control" name="address" placeholder="Address..">{{ old('address') }}</textarea>
        </div>
        <div class="form-group">
          <input type="text" class="bci-custom-input form-control" name="contact_number" value="{{ old('contact_number') }}" placeholder="Contact Number..">
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="subscriber_rate" value="{{ old('subscriber_rate') }}" placeholder="Subscription..">
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="balance" value="{{ old('balance') }}" placeholder="Total Balance..">
        </div>
        <button type="submit" class="bci-custom-button">Save</button>
      </form>
    </div> {{-- form-bottom --}}
  </div> {{-- col-md-8 --}}
</div> {{-- row --}}
@endsection

resources/views/admin/add_subscriber.blade.php
@extends('layouts.main')
@section('title', '| Add new subscriber')
@section('content')
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="form-top">
      <div class="form-top-left">
        <h3>Add New Subscriber</h3>
        <p>Fill in the form below:</p>
      </div>
      <div class="form-top-right">
        <i class="fa fa-pencil"></i>
      </div>
    </div> {{-- form-top --}}
    <div class="form-bottom">
      <form role="form" action="{{ route('store.subscriber') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="status" value="Active">
        <input type="hidden" name="wire_fee" value="10">
        <input type="hidden" name="billing_status" value="Pending">
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="name" value="{{ old('name') }}" placeholder="First Name..">
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="last_name" value="{{ old('last_name') }}" placeholder="Last Name..">
        </div>
        <div class="form-group">
          <textarea required class="bci-custom-input form-control" name="address" placeholder="Address..">{{ old('address') }}</textarea>
        </div>
        <div class="form-group">
          <input type="text" class="bci-custom-input form-control" name="contact_number" value="{{ old('contact_number') }}" placeholder="Contact Number..">
        </div>
        <div class="form-group">
          <input required type="text" id="date_of_installation" class="readonly-bg-custom bci-custom-input form-control" name="date_of_installation" placeholder="Date of Installation.." autocomplete="off">
        </div>
        <div class="form-group">
          <input type="text" class="bci-custom-input form-control" name="wire_length" value="{{ old('wire_length') }}" placeholder="Addition Wire Length(ft)..">
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="subscriber_rate" value="{{ old('subscriber_rate') }}" placeholder="Subscription..">
        </div>
        <div class="form-group">
          <select required class="bci-custom-input form-control" name="deposit" value="{{ old('deposit') }}" placeholder="Deposit..">
              <option class="hide" disabled selected value="">Subscriber Type..</option>
              <option value="regular">Regular Subscriber</option>
              <option value="apartment">Apartment</option>
          </select>
        </div>
        <div class="form-group">
          <input type="text" required class="bci-custom-input form-control" name="installation_fee" value="{{ old('installation_fee') }}" placeholder="Installation Fee..">
        </div>
        <button type="submit" class="bci-custom-button">Save</button>
      </form>
    </div> {{-- form-bottom --}}
  </div> {{-- col-md-8 --}}
</div> {{-- row --}}
@endsection
@section('scripts')
<script type="text/javascript">

  $(function() {

    $("#date_of_installation").keypress(function(event) {
      event.preventDefault();
    });

    $("#date_of_installation").datepicker({
      changeMonth: true,
      changeYear: true,
      dateFormat: 'M/dd/yy',
      yearRange: '1950:2050'
    });

  });
</script>
@endsection

resources/views/admin/billings_subscriber.blade.php
@extends('layouts.main')
@section('title', '| Billings')
@section('content')
@include('includes._modal_fees')
@include('includes._modal_disconnection')
@include('includes._modal_picture')
@include('includes._modal_payment')
@include('includes._modal_reconnection')
@include('includes._modal_add_billing')
<div class="row">
	<div class="col-md-2 col-sm-2">
		@include('includes._side_panel')
	</div> {{-- col-md-2 --}}
	<div class="col-md-10 col-sm-10">
		<div class="form-top">
			<div class="form-top-left">
				<h3>Billing History</h3>
				<p>Name: <i>{{ $subscriber->name }} {{ $subscriber->last_name }}</i></p>
				<p>Address: <i>{{ $subscriber->address }}</i></p>
				<p>Contact Number: <i>{{ $subscriber->contact_number }}</i></p>
				<p>Subscription Rate: <i>{{ $subscriber->subscription->rate }}</i></p>
				@if(strtotime($subscriber->date_of_installation))
				<p>Installation Date: <i>{{ empty($subscriber->date_of_installation) ? '' : Carbon\Carbon::parse($subscriber->date_of_installation)->format('M d, Y') }}</i></p>
				@endif
				@if($subscriber->billings()->first())
				@if($subscriber->deposit->amount != 0)
				<p>Deposit: <i>{{ $subscriber->deposit->amount }}</i></p>
				@endif
				@if($subscriber->status == 'Active')
				<button data-toggle="modal" data-target="#disconnect" class="btn btn-danger">Disconnect</button>
				@else
				<button data-toggle="modal" data-target="#reconnect" class="btn btn-warning">Reconnect</button>
				@endif
				<button class="btn btn-success" data-toggle="modal" data-target="#pay">Pay Balance</button>
				<hr>
				@if($subscriber->deposit->amount != 0)
				<form action="{{ route('post.deposit') }}" method="post">
					<input type="hidden" value="{{ $subscriber->id }}" name="id">
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<button class="btn btn-primary" type="submit">Use Deposit</button>
				</form>
				@endif
				<br>
				<p><b>Lastest Due Date: <i>{{ Carbon\Carbon::parse($subscriber->billings->sortBy('billing_date')->last()->billing_date)->format('M d, Y')  }}</i></b></p>
				<p><b>Total Amount Due: <i>{{ $subscriber->billings->sum('balance') }} </i></b></p>
				@else
				<hr>
				<div class="alert alert-danger">
					<div>This is an initial input user. Please see the index card of this user and input the totality of the balances.</div>
				</div>
				@endif
				<button class="btn btn-success" data-toggle="modal" data-target="#billing-add">Manual Add Billing</button>
			</div>
			<div class="form-top-right">
				<i class="fa fa-history fa-spin"></i>
			</div>
		</div> {{-- form-top --}}
		<div class="form-bottom">
			<table class="table white-text">
				<thead>
					<tr>
						<th>Billing No.</th>
						<th>Billing Date</th>
						{{-- <th>Billing Period Start</th> --}}
						{{-- <th>Billing Period End</th> --}}
						<th>Due Date</th>
						<th>Amount Due</th>
						<th>Balance</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $count = $subscriber->billings->count();?>
					@forelse($billings as $billing)
					<tr>
						<td>{{ $count }}</td>
						<td>{{ Carbon\Carbon::parse($billing->billing_date)->format('M d, Y') }}</td>
						{{-- <td>{{ Carbon\Carbon::parse($billing->billing_period_start)->format('M d, Y') }}</td> --}}
						{{-- <td>{{ Carbon\Carbon::parse($billing->billing_period_end)->format('M d, Y') }}</td> --}}
						<td>{{ Carbon\Carbon::parse($billing->due_date)->format('M d, Y') }}</td>
						<td>{{ $billing->amount_due }}</td>
						<td>{{ $billing->balance }}</td>
						<td>{{ $billing->status }}</td>
						<td>
							<button onclick="view_fees('{{$billing->id}}')" class="btn btn-info" data-toggle="modal" data-target="#fee">View</button>
							{{-- 			@if($firstbilling->id == $billing->id)
							@if($billing->status == 'Pending')
							@if($subscriber->subscription->rate != $billing->amount_due && $billing->amount_due != 0)
							<button class="btn btn-danger" data-toggle="modal" data-target="#billing">Editable(Billing)</button>
							@endif
							@endif
							@endif --}}
							<button class="btn btn-warning" data-toggle="modal" data-target="#billing-{{$billing->id}}">Edit Billing</button>
							<button type="submit" class="btn btn-danger" form="billingform-{{$billing->id}}">Delete</button>
							<form id="billingform-{{$billing->id}}" onsubmit="return confirm('Are you sure you want to delete this ?');" method="POST" action="{{ route('billing.destroy', $billing->id) }}">
								{{ csrf_field() }}
								{{ method_field('DELETE') }}
							</form>
						</td>
					</tr>
					@include('includes._modal_editable_billing')
					<?php $count--;?>
					@empty
					@endforelse
				</tbody>
			</table>
		</div> {{-- form-bottom --}}
	</div> {{-- col-md-10 --}}
</div> {{-- row --}}
@endsection
@section('scripts')
<script type="text/javascript">

		  $(function() {

    $("#edit_billing_date").keypress(function(event) {
      event.preventDefault();
    });

    $("#edit_billing_date").datepicker({
      changeMonth: true,
      changeYear: true,
      dateFormat: 'M/dd/yy',
      yearRange: '1950:2050'
    });

  });

	  $(function() {

    $("#billing_date").keypress(function(event) {
      event.preventDefault();
    });

    $("#billing_date").datepicker({
      changeMonth: true,
      changeYear: true,
      dateFormat: 'M/dd/yy',
      yearRange: '1950:2050'
    });

  });

	$(function() {

		$("#datepay, #datereconnect").keypress(function(event) {
			event.preventDefault();
		});

		$("#datepay, #datereconnect").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: 'M/dd/yy',
			yearRange: '1950:2050'
		});
	});

	var billingFee = "{{ route('billing.fees') }}";

	function view_fees(id)
	{
		$.ajax({
		url: billingFee,
		type:"GET",
		data: {id:id},
		success: function(res) {
			// console.log(res);
			if(res.transfer_fee == null) {
				res.transfer_fee = 0;
			}
			if(res.installation_fee == null) {
				res.installation_fee = 0;
			}
			if(res.reconnection_fee == null) {
				res.reconnection_fee = 0;
			}
			if(res.subscription_fee == null) {
				res.subscription_fee = 0;
			}
			if(res.wire_fee == null) {
				res.wire_fee = 0;
			}
			if(res.wire_length == null) {
				res.wire_length = 0;
			}
			if(res.disconnection_fee == null) {
				res.disconnection_fee = 0;
			}
			if(res.deposit_fee == null) {
				res.deposit_fee = 0;
			}
			if(res.discount == null) {
				res.discount = 0;
			}
			$("#installation_fee").text(res.installation_fee);
			$("#disconnection_fee").text(res.disconnection_fee);
			$("#subscription_fee").text(res.subscription_fee);
			$("#transfer_fee").text(res.transfer_fee);
			$("#deposit_fee").text(res.deposit_fee);
			$("#reconnection_fee").text(res.reconnection_fee);
			$("#wire_fee").text(res.wire_fee);
			$("#discount").text(res.discount);
			$("#wire_length").text(res.wire_length + ' ft.');
			$("#total").text(res.subscription_fee + res.wire_fee + res.installation_fee + res.transfer_fee + res.reconnection_fee + res.deposit_fee + res.disconnection_fee - res.discount);
			}
		})
	}
</script>
@endsection

resources/views/admin/collector_all_daily_report_subscriber.blade.php
@extends('layouts.main')
@section('title', '| Collector Report')
@section('content')
<div class="row">
    <div class="col-md-8 col-sm-8 col-sm-offset-2 col-md-offset-2"">
        <button id="btn_print" class="btn btn-danger form-control">Print</button>
    </div> {{-- col-md-8 --}}
</div> {{-- row --}}
<br>
<div class="row">
    <div class="col-md-8 col-sm-8 col-sm-offset-2 col-md-offset-2"">
        <div class="form-top">
            <div class="form-daterange">
                <div class="form-group">
                    <form action="{{ route('collector.daily-all.subscriber') }}" method="get">
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon search-button-custom">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </span>
                            <input readonly onchange="this.form.submit()" type="text" autocomplete="off" id="report_date" name="date" class="search-input-custom form-control">
                        </div>
                    </form>
                </div>
            </div>
        </div> {{-- form-top --}}
    </div> {{-- col-md-8 --}}
</div> {{-- row --}}
<br>
<div class="row" id="printTable">
    <div class="col-md-8 col-sm-8 col-sm-offset-2 col-md-offset-2">
        <div class="form-top">
            <div class="form-top-left">
                <h3>BroadCable Communications Inc.</h3>
                <h4>Daily Collections</h4>
                <hr>
                <h4>Date : {{ Carbon\Carbon::parse($report)->format('F d, Y') }}</h4>
            </div>
            <div class="form-top-right">
                <i class="fa fa-user"></i>
            </div>
        </div> {{-- form-top --}}
        <div class="form-bottom">
            <div class="table-responsive">
                <table border="1" cellpadding="10" class="table white-text">
                    <thead>
                        <tr>
                            <th width="200">Collector</th>
                            <th>Name</th>
                            <th width="150">Official Receipt</th>
                            <th width="100">Date Paid</th>
                            <th width="100">Amount Paid</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($collections as $key => $value)
                        <tr>
                            <td>{{ $value->collector }}</td>
                            <td>{{ @$value->subscriber()->last_name }}, {{ @$value->subscriber()->name }}</td>
                            <td>{{ $value->official_receipt }}</td>
                            <td>{{ $value->date_paid }}</td>
                            <td>{{ $value->amount_paid }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div> {{-- form-bottom --}}
    </div> {{-- col-md-8 --}}
</div> {{-- row --}}
@endsection
@section('scripts')
<script type="text/javascript">

    function printData()
    {
       var divTable = document.getElementById("printTable");

       newWin= window.open("");
       newWin.document.write(divTable.outerHTML);
       newWin.print();
       newWin.close();
    }

    $('#btn_print').on('click',function(){
        printData();
    });

    $(function() {

        $("#report_date").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'M/dd/yy',
            yearRange: '1950:2050'
        });
    });


</script>
@endsection

resources/views/admin/statement_of_account.blade.php
@extends('layouts.main')
@section('title', '| Billings')
@section('content')
@include('includes._modal_picture')
<div class="row">
	<div class="col-md-2 col-sm-2">
		@include('includes._side_panel')
	</div> {{-- col-md-2 --}}
	<div class="col-md-10 col-sm-10">
		<div class="form-top" id="printTable">
			<div class="form-daterange">
				<center><h3>BroadCable Communications Inc.</h3></center>
				<br>
				<center><h4 class="white-text">Statement of Account</h4></center>
				<hr>
				<br>
				<center><table border="1" cellpadding="10" class="table white-text">
					<tr>
						<td width="300"><p>Account Number</p></td>
						<td><p><b>{{ $subscriber->id }}</b></p></td>
					</tr>
					<tr>
						<td><p>Subscriber Name</p></td>
						<td><p><b>{{ $subscriber->name }} {{ $subscriber->last_name }}</b></p></td>
					</tr>
					<tr>
						<td><p>Billing Address</p></td>
						<td><p><b>{{ $subscriber->address }}</b></p></td>
					</tr>
					<tr>
						<td><p>Monthly Subscription Fee</p></td>
						<td><p><b>{{ $subscriber->subscription->rate }}</b></p></td>
					</tr>
					<tr>
						<td><p>Statement Period</p></td>
						<td><p><b>
						<?php
foreach ($billings->where('status', 'Pending') as $billing) {
    echo Carbon\Carbon::parse($billing->billing_date)->format('M d, Y') . ',';
}
?></b></p>
						</td>
					</tr>
					<tr>
						<td><p>Total Amount Due</p></td>
						<td><p><b>{{ $subscriber->billings->sum('balance') }}</b></p></td>
					</tr>
				</table></center>
			</div>
		</div> {{-- form-top --}}
		@if($subscriber->billings()->first())
		<a href="{{ route('statement.show', $subscriber->id) }}" target="_blank" class="btn btn-danger form-control">Print</a>
		@else
		<a href="{{ route('statement.show', $subscriber->id) }}" class="btn btn-danger form-control">Print</a>
		@endif
		{{-- <button id="btn_print" class="btn btn-danger form-control">Print</button> --}}
	</div> {{-- col-md-10 --}}
</div> {{-- row --}}
@endsection
@section('scripts')
{{-- <script type="text/javascript">

    function printData()
	{
	   var divTable = document.getElementById("printTable");

	   newWin= window.open("");
	   newWin.document.write(divTable.outerHTML);
	   newWin.print();
	   newWin.close();
	}

	$('#btn_print').on('click',function(){
		printData();
	});

</script> --}}
@endsection