routes/web.php
<?php
//Auth
Route::get('/', [
    'uses' => 'Auth\LoginController@getLogin',
    'as' => 'login.get',
]);

Route::post('login', [
    'uses' => 'Auth\LoginController@postLogin',
    'as' => 'login.post',
]);

Route::get('logout', [
    'uses' => 'Auth\LoginController@getLogout',
    'as' => 'logout',
]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Super Admin']], function () {
    Route::resource('activity', 'ActivityLogController');

    Route::get('collectors', [
        'uses' => 'SuperAdminController@getCollectors',
        'as' => 'get.collectors',
    ]);

    Route::post('collector', [
        'uses' => 'SuperAdminController@postCollector',
        'as' => 'post.collector',
    ]);

    Route::patch('collector/remove', [
        'uses' => 'SuperAdminController@patchCollectorRemove',
        'as' => 'patch.collector.remove',
    ]);
});


Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Accountant|Super Admin|Collector']], function () {

    Route::get('subscriber/billing/fees', [
        'uses' => 'SuperAdminController@getFees',
        'as' => 'billing.fees',
    ]);

});

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:Accountant|Super Admin']], function () {

    Route::resource('billing', 'BillingController');

    Route::resource('statement', 'StatementOfAccountController');

    Route::resource('user-subscriber', 'SubscriberController');

    Route::get('/', [
        'uses' => 'SuperAdminController@getDashboard',
        'as' => 'dashboard',
    ]);

    Route::get('inactive/subscribers', [
        'uses' => 'SuperAdminController@getInactiveSubscribers',
        'as' => 'inactive.subscribers',
    ]);

    Route::patch('subscriber/disconnect/', [
        'uses' => 'SuperAdminController@patchDisconnectSubscriber',
        'as' => 'disconnect.subscriber',
    ]);

    Route::patch('inactive/subscriber/reconnect', [
        'uses' => 'SuperAdminController@patchReconnectSubscriber',
        'as' => 'reconnect.subscriber',
    ]);

    Route::post('pay', [
        'uses' => 'SuperAdminController@postPay',
        'as' => 'post.pay',
    ]);

    Route::get('add/subscriber', [
        'uses' => 'SuperAdminController@getAddSubscriber',
        'as' => 'add.subscriber',
    ]);

    Route::post('store/subscriber', [
        'uses' => 'SuperAdminController@getStoreSubscriber',
        'as' => 'store.subscriber',
    ]);

    Route::get('subscriber/billings/{id}', [
        'uses' => 'SuperAdminController@getSubscriberBillings',
        'as' => 'billings.subscriber',
    ]);

    Route::get('subscriber/payments/{id}', [
        'uses' => 'SuperAdminController@getSubscriberPayments',
        'as' => 'payments.subscriber',
    ]);

    Route::get('subscriber/profile/{id}', [
        'uses' => 'SuperAdminController@getSubscriberProfile',
        'as' => 'profile.subscriber',
    ]);

    Route::get('subscriber/statement-of-account/{id}', [
        'uses' => 'SuperAdminController@getSubscriberStatementOfAccount',
        'as' => 'soa.subscriber',
    ]);

    Route::patch('subscriber/profile/patch/name', [
        'uses' => 'SuperAdminController@patchSubscriberName',
        'as' => 'patch.subscriber.name',
    ]);

    Route::patch('subscriber/patch/contact_number', [
        'uses' => 'SuperAdminController@patchSubscriberContactNumber',
        'as' => 'patch.subscriber.contact_number',
    ]);

    Route::patch('subscriber/patch/date_of_installation', [
        'uses' => 'SuperAdminController@patchSubscriberDateOfInstallation',
        'as' => 'patch.subscriber.date_of_installation',
    ]);

    Route::patch('subscriber/patch/rate', [
        'uses' => 'SuperAdminController@patchSubscriberRate',
        'as' => 'patch.subscriber.rate',
    ]);

    Route::patch('subscriber/patch/address', [
        'uses' => 'SuperAdminController@patchSubscriberAddress',
        'as' => 'patch.subscriber.address',
    ]);

    Route::patch('subscriber/patch/picture', [
        'uses' => 'SuperAdminController@patchSubscriberPicture',
        'as' => 'patch.subscriber.picture',
    ]);

    Route::post('subscriber/transfer', [
        'uses' => 'SuperAdminController@postSubscriberTransfer',
        'as' => 'post.transfer',
    ]);

    Route::get('add/old-subscriber', [
        'uses' => 'SuperAdminController@getAddOldSubscriber',
        'as' => 'add.old.subscriber',
    ]);

    Route::post('add/old-subscriber', [
        'uses' => 'SuperAdminController@postAddOldSubscriber',
        'as' => 'post.add.old.subscriber',
    ]);

    Route::patch('subscriber/billing/update', [
        'uses' => 'SuperAdminController@patchSubscriberBilling',
        'as' => 'patch.subscriber.billing',
    ]);

    Route::get('collector/daily/report', [
        'uses' => 'SuperAdminController@getCollectorDailyReport',
        'as' => 'collector.daily',
    ]);

    Route::get('collector/monthly/report', [
        'uses' => 'SuperAdminController@getCollectorMonthlyReport',
        'as' => 'collector.monthly',
    ]);

    Route::get('collector/daily/report-subscriber', [
        'uses' => 'SuperAdminController@getSubscribersReportDaily',
        'as' => 'collector.daily.subscriber',
    ]);

    Route::get('collector/monthly/report-subscriber', [
        'uses' => 'SuperAdminController@getSubscribersReportMonthly',
        'as' => 'collector.monthly.subscriber',
    ]);

    Route::get('collector/daily-all/report-subscriber', [
        'uses' => 'SuperAdminController@getAllSubscribersReportDaily',
        'as' => 'collector.daily-all.subscriber',
    ]);

    Route::post('deposit', [
        'uses' => 'SuperAdminController@postDeposit',
        'as' => 'post.deposit',
    ]);

});

//////////////////////COLLECTOR////////////////////////////////
Route::get('collector-dashboard/subscribers', [
    'uses' => 'CollectorController@getSubscriber',
    'as' => 'collector.subscribers',
    'middleware' => ['role:Collector'],
]);

Route::post('collector-dashboard/pay', [
    'uses' => 'CollectorController@pay',
    'as' => 'collector.pay',
    'middleware' => ['role:Collector'],
]);

Route::get('collector-dashboard/thank-you-page/{id}', [
    'uses' => 'CollectorController@ty',
    'as' => 'collector.ty',
    'middleware' => ['role:Collector'],
]);

Route::get('collector-performance/payments', [
    'uses' => 'CollectorController@performance',
    'as' => 'collector-performance.payments',
    'middleware' => ['role:Collector'],
]);

Route::get('export-subscribers', function () {
    ini_set('memory_limit', '-1');
    try {
        $user = auth()->user();

        $active_subscribers = App\Subscriber::where('status', 'active')
            ->where('collector', $user->name)
            ->get();

        $new = [];

        foreach($active_subscribers as $k => $v) {
                if(number_format($v->billings->sum('balance'),2) == '0.00') {
                    continue;
                }
                $new[$k]['id'] = $v->id;
                $new[$k]['name'] = $v->name.' '.$v->last_name;
                $new[$k]['address'] = $v->address;
                $new[$k]['contact_number'] = $v->contact_number;
                $new[$k]['balance'] = number_format($v->billings->sum('balance'),2);
                // $new[$k]['sort_balance'] = $v->billings->sum('balance');
                $new[$k]['last_payment'] = @$v->payments()->latest()->first()->date_paid;
                $new[$k]['collector'] = @$v->collector;
        }

        // usort($new, function($a, $b) {
        //     return $a['sort_balance'] <=> $b['sort_balance'];
        // });

        $list = collect($new);

        // $list = $xlist->transform(function(array $item) {
        //     return array_except($item, ['sort_balance']);
        // });

        return (new Rap2hpoutre\FastExcel\FastExcel($list))->download('subscribers_collector.xlsx');
    } catch (Exception $e) {
        echo 'Message: ' .$e->getMessage();
    }

})->name('export.subscribers.collector');

/////////////////////////////////////////////////////////////////


Route::get('dashboard/reports', [
    'uses' => 'SuperAdminController@getReports',
    'as' => 'get.reports',
    'middleware' => ['role:Super Admin'],
]);

Route::get('custom-data-input', [
    'uses' => 'CustomDataInputController@getCustomDataInput',
    'as' => 'get.custom',
    'middleware' => ['role:Accountant'],
]);

Route::post('custom-data-input', [
    'uses' => 'CustomDataInputController@postCustomDataInput',
    'as' => 'post.custom',
    'middleware' => ['role:Accountant'],
]);

Route::get('export-user', function () {
    ini_set('memory_limit', '-1');
    return (new Rap2hpoutre\FastExcel\FastExcel(App\Subscriber::where('status', 'Active')->select(['name', 'last_name', 'specific_address', 'address'])->get()))->download('XXX.xlsx');
});

Route::get('export-billing', function () {
    ini_set('memory_limit', '-1');
    try {
        $active_subscribers = App\Subscriber::where('status', 'active')->get();

        $new = [];

        foreach($active_subscribers as $k => $v) {
                if(number_format($v->billings->sum('balance'),2) == '0.00') {
                    continue;
                }
                $new[$k]['id'] = $v->id;
                $new[$k]['name'] = $v->name.' '.$v->last_name;
                $new[$k]['address'] = $v->address;
                $new[$k]['contact_number'] = $v->contact_number;
                $new[$k]['balance'] = number_format($v->billings->sum('balance'),2);
                $new[$k]['sort'] = $v->billings->sum('balance');
        }

        usort($new, function($a, $b) {
            return $a['sort'] <=> $b['sort'];
        });

        $list = collect($new);

        return (new Rap2hpoutre\FastExcel\FastExcel($list))->download('balance.xlsx');
    } catch (Exception $e) {
        echo 'Message: ' .$e->getMessage();
    }

})->name('export.billing');


Route::get('export-fee', function () {
    ini_set('memory_limit', '-1');
    try {

resources/views/includes/_modal_add_billing.blade.php
<div id="billing-add" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add New Billing</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <form action="{{ route('billing.store') }}" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
                            <p>Amount Due</p>
                            <div class="form-group">
                                <input value="{{ old('amount_due') }}" placeholder="Amount Due.." type="text" name="amount_due" class="form-control">
                            </div>
                            <p>Balance</p>
                            <div class="form-group">
                                <input value="{{ old('balance') }}" placeholder="Balance.." type="text" name="balance" class="form-control">
                            </div>

                            <p>Billing Date</p>
                            <div class="form-group">
                                <input type="text" id="billing_date" autocomplete="off" style="border: 1px solid #ccc;" required class="bci-custom-input form-control" name="billing_date" value="{{ old('billing_date') }}" placeholder="Billing date..">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="form-control btn btn-info" value="Submit">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_disconnection.blade.php
<div id="disconnect" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Disconnection</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <h4>Do you want to disconnect ?</h4>
                        <h3>{{ $subscriber->name }}</h3>
                    </div>
                    <br>
                    <div class="row">
                        <form action="{{ route('disconnect.subscriber') }}" method="post">
                            <input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
                            <input type="hidden" name="_method" value="PATCH">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Disconnection Fee" name="amount_due">
                            </div>

                            <h4>Notes</h4>
                            <div class="form-check">
                              <input class="form-check-input" type="radio" name="note" id="exampleRadios1" value="Not Paid" checked>
                              <label class="form-check-label" for="exampleRadios1">
                                Not Paid
                              </label>
                            </div>
                            <div class="form-check">
                              <input class="form-check-input" type="radio" name="note" id="exampleRadios2" value="End of Contract">
                              <label class="form-check-label" for="exampleRadios2">
                                End of Contract
                              </label>
                            </div>
                            <div class="form-check">
                              <input class="form-check-input" type="radio" name="note" id="exampleRadios3" value="Upgrade to Internet">
                              <label class="form-check-label" for="exampleRadios3">
                                Upgrade to Internet
                              </label>
                            </div>

                            <div class="form-group" style="margin-top: 20px;">
                                <input type="submit" class="btn btn-info form-control" value="Confirm">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
            <div class="modal-footer">
            </div> {{-- modal-footer --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_editable_billing.blade.php
<div id="billing-{{$billing->id}}" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editable Billing</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <form action="{{ route('billing.update', $billing->id) }}" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="_method" value="PATCH">
                            <input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
                            <p>Amount Due</p>
                            <div class="form-group">
                                <input value="{{ $billing->amount_due }}" placeholder="Amount Due.." type="text" name="amount_due" class="form-control">
                            </div>
                            <p>Balance</p>
                            <div class="form-group">
                                <input value="{{ $billing->balance }}" placeholder="Balance.." type="text" name="balance" class="form-control">
                            </div>
                                                                            <?php
$carbonFormat = Carbon\Carbon::createFromFormat('Y-m-d', $billing->billing_date);
$billing_date = Carbon\Carbon::parse($carbonFormat)->format('M/d/Y');

?>
                            <p>Billing Date</p>
                            <div class="form-group">
                                <input type="text" id="edit_billing_date" autocomplete="off" style="border: 1px solid #ccc;" required class="bci-custom-input form-control" name="billing_date" value="{{ $billing_date }}" placeholder="Billing date..">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="form-control btn btn-info" value="Submit">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_fees.blade.php
<div id="fee" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Summary</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-5">
                            <p>Subscription Fee:</p>
                            <p>Installation Fee:</p>
                            <p>Deposit Fee:</p>
                            <p>Transfer Fee:</p>
                            <p>Disconnection Fee:</p>
                            <p>Reconnection Fee:</p>
                            <p>Wire:</p>
                            <p>Wire Fee(1 ft. = ₱10):</p>
                            <hr>
                            <p>Discount:</p>
                            <hr>
                            <p>Total:</p>
                        </div>
                        <div class="col-md-5">
                            <p><i id="subscription_fee"></i>&nbsp;</p>
                            <p><i id="installation_fee"></i>&nbsp;</p>
                            <p><i id="deposit_fee"></i>&nbsp;</p>
                            <p><i id="transfer_fee"></i>&nbsp;</p>
                            <p><i id="disconnection_fee"></i>&nbsp;</p>
                            <p><i id="reconnection_fee"></i>&nbsp;</p>
                            <p><i id="wire_length"></i>&nbsp;</p>
                            <p><i id="wire_fee"></i>&nbsp;</p>
                            <hr>
                            <p><i id="discount"></i>&nbsp;</p>
                            <hr>
                            <p><b id="total"></b>&nbsp;</p>
                        </div>
                    </div>
                </div>
            </div> {{-- modal-body --}}
            <div class="modal-footer">
            </div> {{-- modal-footer --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_payment.blade.php
<div id="pay" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Payment</h4>
                <br>
                Name : <b>{{$subscriber->name}}</b>
                <br>
                Balance : <b>{{$subscriber->billings->sum('balance')}}</b>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <form action="{{ route('post.pay') }}" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="subscriber_id" value="{{$subscriber->id}}">
                            <input type="hidden" name="billing_pending" value="Pending">
                            <input type="hidden" name="billing_paid" value="Paid">
                            <input type="hidden" name="billing_free" value="Free">
                            <div class="form-group">
                                <input onkeypress="return isNumberKey(event)" placeholder="Official Receipt.." type="number" name="official_receipt" class="form-control">
                            </div>
                            <div class="form-group">
                                <select required class="form-control" name="collector" autocomplete="off">
                                    <option class="hide" disabled selected value="">Collector..</option>
                                    @foreach($collectors->users as $collector)
                                    <option value="{{ $collector->name }}">{{ $collector->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <input required placeholder="Date Paid.." type="text" id="datepay" autocomplete="off" name="date_paid" class="form-control">
                            </div>
                            <div class="form-group">
                                <input required placeholder="Amount.." type="text" name="amount_paid" class="form-control">
                            </div>
                            <div class="form-group">
                                <input placeholder="Discount.." type="text" name="discount" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="form-control btn btn-info" value="Submit">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}
<script type="text/javascript">
function isNumberKey(evt) {
    var charCode = (evt.which) ? evt.which : event.keyCode;
    if ((charCode < 48 || charCode > 57))
        return false;

    return true;
}
</script>

resources/views/includes/_modal_picture.blade.php
<div id="picture" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <img src="{{ asset('img/'.$subscriber->picture) }}" height="500" width="500" class="thumbnail img-responsive" alt="picture">
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_reconnection.blade.php
<div id="reconnect" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Reconnection</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <h4>Do you want to reconnect ?</h4>
                        <h3>{{ $subscriber->name }}</h3>
                    </div>
                    <br>
                    <div class="row">
                        <form action="{{ route('reconnect.subscriber') }}" method="post">
                            <input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
                            {{-- <input type="hidden" name="amount_due" value="150"> --}}
                            <input type="hidden" name="_method" value="PATCH">
                            <input type="hidden" name="status" value="Pending">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Reconnection Fee" name="amount_due">
                            </div>
                            <div class="form-group">
                                <input required type="text" id="datereconnect" class="readonly-bg-custom form-control" name="reconnection_date" placeholder="Date of Reconnection.." autocomplete="off">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-info form-control" value="Confirm">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
            <div class="modal-footer">
            </div> {{-- modal-footer --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_modal_transfer.blade.php
<div id="transfer" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Transfer</h4>
            </div> {{-- modal-header --}}
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <h4>Transfer fee will be process?</h4>
                    </div>
                    <br>
                    <div class="row">
                        <form action="{{ route('post.transfer') }}" method="post">
                            <input type="hidden" name="id" value="{{ $subscriber->id }}">
                            <input type="hidden" name="wire_fee" value="10">
                            <input type="hidden" name="billing_status" value="Pending">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="form-group">
                                <input required type="text" id="billing_date" name="billing_date" class="readonly-bg-custom form-control" placeholder="Date of transfer.." autocomplete="off">
                            </div>
                            <div class="form-group">
                                <input type="text" name="wire_length" class="form-control" placeholder="Additional Wire Length(ft)..">
                            </div>
                            <div class="form-group">
                                <input required type="text" name="transfer_fee" class="form-control" placeholder="Transfer Fee..">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-info form-control">Confirm</button>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> {{-- modal-body --}}
            <div class="modal-footer">
            </div> {{-- modal-footer --}}
        </div> {{-- modal-content --}}
    </div> {{-- modal-dialog --}}
</div> {{-- modal --}}

resources/views/includes/_side_panel.blade.php
<center>
<a class="thumbnail" href="#" {{ $subscriber->picture != 'default.jpg' ? 'data-toggle=modal' : ''}} data-target="#picture">
	<img src="{{ asset('img/'.$subscriber->picture) }}" height="200" width="200" class="img-responsive" alt="picture">
</a>
@if(Request::is('dashboard/subscriber/profile/*'))
<div class="row">
	<button class="btn btn-info" onclick="document.getElementById('picture_upload').click();">
		<i class="fa fa-camera" aria-hidden="true"></i>
	</button>

	<button class="btn btn-danger" onclick="document.getElementById('form_delete').submit();">
		<i class="fa fa-times" aria-hidden="true"></i>
	</button>
	<form id="form_delete" role="form" action="{{ route('patch.subscriber.picture') }}" method="POST" files="true" enctype="multipart/form-data">
		<input type="file" name="picture" class="hide" value=""/>
		<input type="hidden" name="_method" value="PATCH">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
		<div class="form-group">
	</form>
	<form role="form" action="{{ route('patch.subscriber.picture') }}" method="POST" files="true" enctype="multipart/form-data">
		<input type="file" id="picture_upload" name="picture" class="hide" onchange="this.form.submit()"/>
		<input type="hidden" name="_method" value="PATCH">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<input type="hidden" name="subscriber_id" value="{{ $subscriber->id }}">
	</form>
</div>
@endif
</center>
<br>
<div class="text-center">
	<p><b id="subscriber_name_side_panel">{{ $subscriber->name }}</b></p>
</div>
<hr>
<div class="list-group">
	<a href="{{ route('billings.subscriber', $subscriber->id) }}" class="{{ Request::is('dashboard/subscriber/billings/*') ? "active" : "" }} list-group-item">Billing History</a>
	<a href="{{ route('payments.subscriber', $subscriber->id) }}" class="{{ Request::is('dashboard/subscriber/payments/*') ? "active" : "" }} list-group-item">Payments</a>
	<a href="{{ route('profile.subscriber', $subscriber->id) }}" class="{{ Request::is('dashboard/subscriber/profile/*') ? "active" : "" }} list-group-item">Subscriber Settings</a>
	<a href="{{ route('soa.subscriber', $subscriber->id) }}" class="{{ Request::is('dashboard/subscriber/statement-of-account/*') ? "active" : "" }} list-group-item">Statement of Account</a>
</div> {{-- list-group --}}